[package]
name = "tb_app"
version = "0.1.0"
authors = ["dahai-f <1119369173@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tb_core = { path = "../tb_core" }
tb_ecs = { path = "../tb_ecs" }
tb_engine = { path = "../tb_engine" }
tb_plugin = { path = "../tb_plugin" }
